### ISSUE TITLE
Partials no longer cached

### ISSUE THREAD

**Issue by ConnorWiseman** [ConnorWiseman/koa-hbs-renderer#4]
See [this](https://github.com/ConnorWiseman/koa-hbs-renderer/pull/2#issuecomment-317009019). The test for this gives a false positive-- because I wrote it in such a way that it didn't actually test whether or not the cache was getting hit (i.e., only for coverage).

Considering writing some logic to preserve the desired behavior on top of [#unregisterPartial](http://handlebarsjs.com/reference.html#base-unregisterPartial).

**Comment by dhershman1** [comment]
Do partials need to be cached? Once they're registered to handlebars it can grab then whenever it needs to. There is no need for the package to go in and manually obtain them each time.

**Comment by ConnorWiseman** [comment]
This is true! Looking [under the hood with Handlebars](https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/base.js#L49), though, it's not doing anything that the cache managed by this package doesn't do already, so rather than limit functionality _or_ try to decorate the Handlebars environment with extra functionality, I brought the cache expiration mechanism for partials back from 0.2.x.

It's only enabled when the package is running in a development environment, and for performance reasons it should probably be disabled in production applications. In production, partials are loaded up once the first time a view gets rendered and from that point onward they just get read from the in-memory cache.

I hope that's an acceptable compromise between wanted features!

**Comment by dhershman1** [comment]
Makes sense to me . Lol
