### ISSUE TITLE
THANKS!

### ISSUE THREAD

**Issue by Extarys** [ConnorWiseman/koa-hbs-renderer#5]
Finally, a handlebars library for Koa that actually support every features of handlebars easily.

(I needed layouts but all other libraries makes it a pain in the butt)

Thank you so much for this and for the time you put in this. Please don't give up - I'm not good enough to contribute to this but I hope my thank you will help you continue this.

Before sending this I confirmed without too much extensive tests that my primary features are working - AWESOME xxxxx

**Comment by ConnorWiseman** [comment]
No worries! @dhershman1 deserves a lot of the credit for the pull requests that introduced more of the features. Truth be told, I just wanted something with support for layouts, too.
