### ISSUE TITLE
Other package Cache vs this expires

### ISSUE THREAD

**Issue by Extarys** [ConnorWiseman/koa-hbs-renderer#6]
Does this **expires** option act like other **koa-hbs**, **koa-view** cache option?

I thought it was like **PHP** where the **templates** where saved on disk - Does all nodejs cache act in-memory?

Thanks for clarifying this :)

**Comment by ConnorWiseman** [comment]
I'm not intricately familiar with how those other packages cache their template objects, so I really can't say!

As far as I know, and for this package, the cache has to sit in memory-- compiled [Handlebars](https://github.com/wycats/handlebars.js) templates take the form of functions, which can't really be written to disk and read back without introducing a nasty dependency on [eval](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval) or something similar, which could cause some serious security issues.

**Comment by Extarys** [comment]
Thanks for clarifying this! Good point
